version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: easygenerator

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo-data: